### PR TITLE
G4.17 insert or select record genotypes loader

### LINKED ISSUE #17: Functionality to insert or select a record using the Genotypes Loader Plugin
Code from T3: https://github.com/UofS-Pulse-Binfo/genotypes_loader/blob/1005f2ff8ad89ad543f2a76834f0247f9c697925/api/genotypes_loader.api.inc#L55

This is a generic function that is given the chado table and the records to select and/or insert. 

Parameters:
* record_type: A human-readable term for your record for error messages.
* table: The chado table to select/insert from/into.
* mode: One of 0 (Select Only), 1 (Insert Only), 2 (Insert & Select)
* select_values: An array of [table column] => [value] mappings. These values will be used for both the select and the insert, but are specific to select
* insert_values: An array of [table column] => [value] mappings that is specific to the insert. This is not required if mode is select only, and will be combined with select values for an insert.

Returns:
 *   The value of the primary key for the inserted/selected record or FALSE if failed.

### PR DESCRIPTION
**Pull request by carolyncaron**
Issue #17 

## Description
This PR implements a method for selecting and inserting records within Chado. It does various validation such as ensuring a record exists if selecting, or doesn't exist if only inserting is allowed. Selecting a record if it exists and inserting if it doesn't is also an option. @laceysanderson and I settled on the name **getRecordPkey()** (vs the old name: genotypes_loader_helper_add_record_with_mode) for both brevity and to indicate what the function returns.

## Testing?
Automated tests were developed for the following:
- Select only an existing record
- Using an invalid mode (value of 5 instead of 0, 1, or 2)
- Insert only of an existing record
- Select/Insert of a record that is duplicated in Chado
- Insert only of a record with an invalid field ("blah" for organism)
- Select only of a non-existing record
- Insert only of a non-existing record

Additionally, I added a test for the plugin manager:
- Provide an invalid organism ID

I am open to suggestions if you think of a case that hasn't been tested :)

Manual testing of the current functionality cannot be done at this time. However, you can clone this repository, access the docker image for this module and tweak the automated tests in the `tests/src/Functional/GenotypesLoader/Subclass` folder and the example input files located in `tests/src/Fixtures`. 

```
docker build --tag=trpcultivate:latest .
docker run --publish=80:80 --name=trpcultivate -tid --volume=`pwd`:/var/www/drupal9/web/modules/contrib/TripalCultivate-Genetics trpcultivate:latest
docker exec trpcultivate service postgresql restart
```
Checkout this branch, then run the tests using `docker exec trpcultivate phpunit --group "Genotypes Loader"`

### CODE REVIEW

File: trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderInterface.php [hunk 1]
```diff
@@ -136,4 +136,39 @@ public function getInputFilepath();
...
+   *   primary key. 
+   *   For example, the user may prefer to add stocks to the database
+   *   manually or expects all of them to exist, so chooses a mode of 0 (select 
+   *   only) so they will be informed if a germplasm does not already exist by
+   *   an error.
+   *   This must be one of: 0 (Select Only), 1 (Insert Only), 2 (Insert & Select)
+   * @param array $select_values
+   *   An array of [table column] => [value] mappings. 
+   *   These values will be used for both the select and the insert, but are 
+   *   specific to selecting the right record.
```
Comment (laceysanderson) [inline trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderInterface.php]:
```suggestion
   *   specific to selecting the right record and thus are used in the 
   *   conditions (i.e. WHERE clause) of the query.
```

File: trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderInterface.php [hunk 2]
```diff
@@ -136,4 +136,39 @@ public function getInputFilepath();
...
+   * @param array $insert_values
+   *   An array of [table column] => [value] mappings that is specific to the 
+   *   insert. This is not required if mode is select only, and will be combined 
+   *   with select values for an insert.
```
Comment (laceysanderson) [inline trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderInterface.php]:
```suggestion
   *   with select values for an insert. More specifically, the values for all 
   *   columns set in the new record are defined in the combined select + insert
   *   values arrays.
```

File: trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php [hunk 3]
```diff
@@ -356,4 +356,99 @@ public function getInputFilepath() {
...
+    * {@inheritdoc}
+    */
+  public function getRecordPkey(string $record_type, string $table, int $mode, array $select_values, array $insert_values = []) {
+    
+    // Check if the mode is one of the 3 options, throw an exception otherwise 
+    $valid_modes = [0, 1, 2];
+
+    if (!in_array($mode, $valid_modes)) {
+      throw new \Exception(
+        t("The specified mode is not valid. (mode=@mode)." , ['@mode'=>$mode])
```
Comment (laceysanderson) [inline trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php]:
```suggestion
        t("The specified mode is not valid (mode=@mode)." , ['@mode'=>$mode])
```

File: trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php [hunk 4]
```diff
@@ -356,4 +356,99 @@ public function getInputFilepath() {
...
+    // Set some variables to abstract mode
+    $select_only = 0;
+    $insert_only = 1;
+    $both = 2;
+
+    // the name of the primary key.
+    $pkey = $table . '_id';
+
+    // Open a db connection
+    $connection = \Drupal::service('tripal_chado.database');
```
Comment (laceysanderson) [inline trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php]: In the future we will want to use dependency injection for this.

File: trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php [hunk 5]
```diff
@@ -356,4 +356,99 @@ public function getInputFilepath() {
...
+    // First we select the record to see if it already exists.
+    $query = $connection->select('1:' . $table, 't');
+    $query->fields('t', [$pkey]);
+    // Iterate through our select_values array
+    foreach($select_values as $key => $value) {
+      $query->condition('t.'.$key, $value, '=');
+    }
+    $record = $query->execute()->fetchAll();
+
+    // If it exists and the mode is 1 (Insert Only), then return an error to drush.
```
Comment (laceysanderson) [inline trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php]:
```suggestion
    // If it exists and the mode is 1 (Insert Only), then throw an exception.
```

File: trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php [hunk 6]
```diff
@@ -356,4 +356,99 @@ public function getInputFilepath() {
...
+      else {
+        return $record[0]->{$pkey};
+      }
+    }
+
+    // If more then one result is returned then this is NOT UNIQUE and we should report an
+    // error to the user - not just run with the first one.
+    elseif (sizeof($record) > 1) {
+      throw new \Exception(
+        t("Record '@record_type' is not unique. (mode=@mode). Values: " .print_r($select_values, TRUE), ['@record_type'=>$record_type, '@mode'=>$mode])
```
Comment (laceysanderson) [inline trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php]:
```suggestion
        t("Record '@record_type' is not unique (mode=@mode). Values: " .print_r($select_values, TRUE), ['@record_type'=>$record_type, '@mode'=>$mode])
```

File: trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php [hunk 7]
```diff
@@ -356,4 +356,99 @@ public function getInputFilepath() {
...
+      );
+      return FALSE;
+    }
+
+    // If there is no pre-existing sample but we've been given permission to create it,
```
Comment (laceysanderson) [inline trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php]:
```suggestion
    // If there is no pre-existing record but we've been given permission to create it,
```

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php [hunk 8]
```diff
@@ -154,5 +157,100 @@ public function testGenotypesLoaderPluginBase(){
     // Get sample filepath
     $grabbed_sample_file_path = $plugin->getSampleFilepath();
     $this->assertEquals($sample_file_path, $grabbed_sample_file_path, "The sample filepath grabbed by the getter method does not match.");
+
+    /****************************************************************************
+     *  TESTS for method getRecordPkey()
+     ****************************************************************************/
+    // Get the primary key of the organism we created using getRecordPkey()
+    $organism_id = $plugin->getRecordPkey('Organism', 'organism', 0, array(
```
Comment (laceysanderson) [inline trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]:
```suggestion
    $grabbed_organism_id = $plugin->getRecordPkey('Organism', 'organism', 0, array(
```

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php [hunk 9]
```diff
@@ -154,5 +157,100 @@ public function testGenotypesLoaderPluginBase(){
...
+    try {
+      $organism_id = $plugin->getRecordPkey('Organism', 'organism', 5, array(
+        'genus' => $genus,
+        'species' => $species
+      ));
+    }
+    catch ( \Exception $e ) { 
+      $exception_caught = TRUE;
+    }
+    $this->assertTrue($exception_caught, "Did not catch exception for using an inavlid mode (5).");
```
Comment (laceysanderson) [inline trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]:
```suggestion
    $this->assertTrue($exception_caught, "Did not catch exception for using an invalid mode (5).");
```

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php [hunk 10]
```diff
@@ -154,5 +157,100 @@ public function testGenotypesLoaderPluginBase(){
...
+
+    // Try to insert a record that already exists and catch the expected exception
+    $exception_caught = FALSE;
+    try {
+      $organism_id = $plugin->getRecordPkey('Organism', 'organism', 1, array(
```
Comment (laceysanderson) [inline trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]: You keep redefining organism_id which can cause unexpected test results. In this case you expect an exception so there is no need to catch the return value.

```suggestion
      $plugin->getRecordPkey('Organism', 'organism', 1, array(
```

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php [hunk 11]
```diff
@@ -154,5 +157,100 @@ public function testGenotypesLoaderPluginBase(){
...
+        'species' => $species
+      ));
+    } 
+    catch ( \Exception $e ) { 
+      $exception_caught = TRUE;
+    }
+    $this->assertTrue($exception_caught, "Did not catch exception for trying to insert a duplicate.");
+
+    // Enter a duplicate record to trigger an exception
+    $organism_id = $connection->insert('1:organism')
```
Comment (laceysanderson) [inline trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]:
```suggestion
    $second_organism_id = $connection->insert('1:organism')
```

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php [hunk 12]
```diff
@@ -154,5 +157,100 @@ public function testGenotypesLoaderPluginBase(){
...
+    ->fields(['genus', 'species'])
```
Comment (laceysanderson) [inline trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]: Why is there a `fields` added to an insert query 🤔

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php [hunk 13]
```diff
@@ -154,5 +157,100 @@ public function testGenotypesLoaderPluginBase(){
...
+        'species' => "silvestris"
+      ));
+    }
+    catch ( \Exception $e ) { 
+      $exception_caught = TRUE;
+    }
+    $this->assertTrue($exception_caught, "Did not catch exception for selecting a non-existing record.");
+
+    // Now that we confirmed the new record doesn't exist, try to insert it
+    $new_organism_id = $plugin->getRecordPkey('Organism', 'organism', 1, array('genus' => "Felis"), array('species' => "silvestris"));
```
Comment (laceysanderson) [inline trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]: You want an assert here too. Even just to check that $new_organism_id is not FALSE.

File: trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php (hunk 4 above)
Comment (carolyncaron) [reply trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php]: Addressed this with commit [48f9e51](https://github.com/TripalCultivate/TripalCultivate-Genetics/pull/20/commits/48f9e5110685e5cbc0ecedd72302531aafc13b6e) :tada:

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php (hunk 8 above)
Comment (carolyncaron) [reply trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]: Addressed in commit [336b7ba](https://github.com/TripalCultivate/TripalCultivate-Genetics/pull/20/commits/336b7ba8d341204ca2c084dcfde51563a4c06a0f)

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php (hunk 11 above)
Comment (carolyncaron) [reply trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]: Addressed in commit [336b7ba](https://github.com/TripalCultivate/TripalCultivate-Genetics/pull/20/commits/336b7ba8d341204ca2c084dcfde51563a4c06a0f)

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php (hunk 13 above)
Comment (carolyncaron) [reply trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]: Addressed in commit [336b7ba](https://github.com/TripalCultivate/TripalCultivate-Genetics/pull/20/commits/336b7ba8d341204ca2c084dcfde51563a4c06a0f)

File: trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php (hunk 12 above)
Comment (carolyncaron) [reply trpcultivate_genotypes/tests/src/Functional/GenotypesLoader/GenotypesLoaderBasePluginTest.php]: All of my inserts are using fields. 😬 But I'm not sure why it's wrong... I've been following the Drupal documentation here: https://www.drupal.org/docs/drupal-apis/database-api/insert-queries#compact-form 
I guess I can see that "fields" may not be necessary at all if the name of the field is also included in "values". What about in [this case](https://github.com/TripalCultivate/TripalCultivate-Genetics/blob/336b7ba8d341204ca2c084dcfde51563a4c06a0f/trpcultivate_genotypes/src/GenotypesLoader/GenotypesLoaderPluginBase.php#LL202C2-L205C1)? Can I use "values" instead of "fields" altogether?

      // Insert all of our values
      $result = $this->connection->insert('1:' . $table)
        ->fields($values)
        ->execute();

**Review by laceysanderson — COMMENTED** [review]
Changes so far look good!

Only thing left is the use of both fields() and values() for a single insert 🙃

**Review by laceysanderson — APPROVED** [review]
Perfect 👍
